serial:
  device: {{ device }}
  timeout: 0

healthcheck:
  frequency: 5

snmp:
  retry:
    max_attempts: 3
    delay: 5
    timeout: 5

banks:
  '001':
    snmp:
      v1:
        public_community: {{ community_name }}
        private_community: {{ community_name }}
      ip_address: {{ ip_address }}
      port: {{ port }}
      outlets:
        '001': {{ oid }}
        '002': {{ oid }}
  '002':
    snmp:
      v2:
        public_community: {{ community_name }}
        private_community: {{ community_name }}
      ip_address: {{ ip_address }}
      port: {{ port }}
      outlets:
        '001': {{ oid }}
        '002': {{ oid }}
  '003':
    snmp:
      v3:
        user: {{ snmp_user }}
        auth_protocol: {{ snmp_auth }}
        auth_passphrase: '{{ snmp_auth_passphrase }}'
        priv_protocol: {{ snmp_priv }}
        priv_passphrase: '{{ snmp_priv_passphrase }}'
      ip_address: {{ ip_address }}
      port: {{ port }}
      outlets:
        '001': {{ oid }}
        '002': {{ oid }}
